// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2idbGnV9Y5TnvyXya_y2Za1x-B9T0R4',
    appId: '1:945689156630:web:aaf0a7bb94001106346937',
    messagingSenderId: '945689156630',
    projectId: 'racunko-78d94',
    authDomain: 'racunko-78d94.firebaseapp.com',
    storageBucket: 'racunko-78d94.appspot.com',
    measurementId: 'G-8HN2SC6YP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKWiXiI6SHPX2ski3OV5YRVmwzmUamqc',
    appId: '1:945689156630:android:534e4dee5580f208346937',
    messagingSenderId: '945689156630',
    projectId: 'racunko-78d94',
    storageBucket: 'racunko-78d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzfRRXdocZk-ieN2JfEODKTrJA-5Em2uI',
    appId: '1:945689156630:ios:e17e4ccaa6c606e2346937',
    messagingSenderId: '945689156630',
    projectId: 'racunko-78d94',
    storageBucket: 'racunko-78d94.appspot.com',
    iosBundleId: 'com.josipkilic.racunko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzfRRXdocZk-ieN2JfEODKTrJA-5Em2uI',
    appId: '1:945689156630:ios:e17e4ccaa6c606e2346937',
    messagingSenderId: '945689156630',
    projectId: 'racunko-78d94',
    storageBucket: 'racunko-78d94.appspot.com',
    iosBundleId: 'com.josipkilic.racunko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2idbGnV9Y5TnvyXya_y2Za1x-B9T0R4',
    appId: '1:945689156630:web:553f521e575601ae346937',
    messagingSenderId: '945689156630',
    projectId: 'racunko-78d94',
    authDomain: 'racunko-78d94.firebaseapp.com',
    storageBucket: 'racunko-78d94.appspot.com',
    measurementId: 'G-RVVYJV6F0K',
  );
}
